site_name: Crucible Documentation
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  #custom_dir: !ENV [THEME_DIR, "material"]
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - toc.integrate
  logo: assets/img/crucible-icon-c-alpha.svg
  favicon: assets/img/crucible-icon-c-alpha.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: red

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: red
nav:
  - Home: index.md
  - Player:
    - player/index.md
    - Views:
      - player/views/index.md
      - Create a new View: player/views/player-create-new-view.md
      - Copy and Paste Text: player/views/player-copy-and-paste-text.md
      - Power a VM on or off: player/views/player-power-a-vm-on-or-off.md
      - Upload Files: player/views/player-how-to-upload-files.md
      - Follow a Participant: player/views/player-follow-user.md
    - Applications:
      - player/applications/index.md
      - Create a new App Template: player/applications/player-create-new-app-template.md
    - Maps:
      - player/maps/index.md
  - Caster:
    - caster/index.md
    - Projects:
      - caster/projects/index.md
      - Directories: caster/projects/caster-directory.md
      - Files: caster/projects/caster-files.md
      - Modules: caster/projects/caster-modules.md
      - Workspace: caster/projects/caster-workspace.md
      - Run, Plan, and Apply: caster/projects/caster-run-plan-apply.md
    - Hosts: 
      - caster/hosts/index.md
    - Caster Terraform Configuration: 
      - caster/terraform/index.md
  - Steamfitter: 
    - steamfitter/index.md
    - Scenario Templates: 
      - steamfitter/scenario-templates/index.md
    - Scenarios: 
      - steamfitter/scenarios/index.md
    - Steamfitter Tasks: 
      - steamfitter/tasks/index.md
    - Steamfitter History: 
      - steamfitter/history/index.md
  - Alloy:
    - alloy/index.md
    - Definitions:
      - alloy/definitions/index.md  
      - Create an Alloy Definition: alloy/definitions/alloy-how-to-create-a-definition.md
  - Blueprint:
    - blueprint/index.md
    - Dashboard:
      - blueprint/dashboard/index.md
    - MSELs:
      - blueprint/msels/index.md
      - Create/Delete: blueprint/msels/blueprint-msel-create-delete.md
      - Download: blueprint/msels/blueprint-msel-download.md
      - Upload/Copy: blueprint/msels/blueprint-msel-upload-copy.md
    - Edit Msels:
      - blueprint/edit/index.md
      - Info: blueprint/edit/blueprint-msel-info.md
      - Roles: blueprint/edit/blueprint-msel-roles.md
      - Data Fields: blueprint/edit/blueprint-msel-datafields.md
      - Organizations: blueprint/edit/blueprint-msel-organizations.md
      - Injects: blueprint/edit/blueprint-msel-injects.md
      - Exercise View: blueprint/edit/blueprint-msel-overview.md
  - CITE:
    - cite/index.md
    - Dashboard:
      - cite/dashboard/index.md
      - Active Incident & Moves: cite/dashboard/cite-dashboard-moves.md
      - Dashboard/Scoresheet Toggle: cite/dashboard/cite-dashboard-toggle.md
      - Situation Description/Date & Time: cite/dashboard/cite-dashboard-date.md
      - Score Summary: cite/dashboard/cite-dashboard-score.md
      - Actions To Consider: cite/dashboard/cite-dashboard-actions.md
      - Roles: cite/dashboard/cite-dashboard-roles.md      
    - Scoresheet:
      - cite/scoresheet/index.md
      - User: cite/scoresheet/cite-scoresheet-user.md
      - Team: cite/scoresheet/cite-scoresheet-team.md
      - Team Average: cite/scoresheet/cite-scoresheet-team-average.md
      - Group Average: cite/scoresheet/cite-scoresheet-group-average.md
      - Official: cite/scoresheet/cite-scoresheet-official.md
      - Submit: cite/scoresheet/cite-scoresheet-submit.md
      - Clear: cite/scoresheet/cite-scoresheet-clear.md
      - Preset: cite/scoresheet/cite-scoresheet-preset.md
      - Dashboard/Scoresheet Toggle: cite/scoresheet/cite-scoresheet-toggle.md
      - Actions & Roles Settings: cite/scoresheet/cite-scoresheet-settings.md
    - Actions & Roles:
      - cite/roles-permissions/index.md
      - Actions Add: cite/roles-permissions/cite-actions-plus.md
      - Actions Edit: cite/roles-permissions/cite-actions-edit.md
      - Actions Delete: cite/roles-permissions/cite-actions-delete.md
      - Roles Add: cite/roles-permissions/cite-roles-plus.md
      - Roles Edit: cite/roles-permissions/cite-roles-edit.md
      - Roles Delete: cite/roles-permissions/cite-roles-delete.md
    - User Roles & Permissions:
      - cite/user-roles-permissions/index.md
      - User: cite/user-roles-permissions/cite-user-permissions.md
      - Roles: cite/user-roles-permissions/cite-user-entered-roles.md
  - Gallery:
    - gallery/index.md
    - Archive:
      - gallery/archive/index.md
    - Wall:
      - gallery/wall/index.md
